version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs: 
  test: 
    docker: 
      - image: cimg/node:14.13.0
        environment:
          DB_TYPE: mysql
          DB_HOST: localhost
          DB_USER: root
          DB_NAME: loki
      - image: circleci/mysql:8.0.4
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'
          - MYSQL_USER: root
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: npm install
      - run: 
          name: Create Database
          command: npm run exec db:fresh
      - run: 
          name: Database migration
          command: npm run exec migrate
      - run: 
          name: Database seed
          command: npm run exec db:seed
      - run:
          name: Run Unit Tests
          command: npm run test:unit
