version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs: 
  test: 
    docker: 
      - image: cimg/node:14.13.0
        environment:
          DB_TYPE: mysql
          DB_HOST: localhost
          DB_USER: root
          DB_NAME: loki
      - image: circleci/mysql:8.0.4
        command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin && mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE loki '&& mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE loki_test'"
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'
          - MYSQL_USER: root
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: npm install
      - run: 
          name: Database migration
          command: npm run exec migrate
      - run: 
          name: Database seed
          command: npm run exec db:seed
      - run:
          name: Run Unit Tests
          command: npm run test:unit
